# Generated by Django 4.1.2 on 2022-10-30 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=90)),
                ('matricula', models.CharField(max_length=9, unique=True)),
                ('prod_contr', models.IntegerField()),
                ('prod_pos', models.IntegerField()),
                ('prod_ap', models.FloatField()),
            ],
        ),
    ]
