# Generated by Django 4.1.2 on 2022-10-31 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedor',
            name='matricula',
            field=models.CharField(max_length=9, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='prod_ap',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='prod_contr',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='prod_pos',
            field=models.IntegerField(null=True),
        ),
    ]
