# Generated by Django 4.1.3 on 2022-11-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_vendedor_matricula_alter_vendedor_prod_ap_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta_ind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contr', models.IntegerField(null=True)),
                ('pos', models.IntegerField(null=True)),
                ('pre_rec', models.IntegerField(null=True)),
                ('servico', models.FloatField(null=True)),
                ('aparelho', models.FloatField(null=True)),
                ('acessorio', models.IntegerField(null=True)),
                ('seguro', models.IntegerField(null=True)),
            ],
        ),
    ]
