# Generated by Django 4.1.3 on 2022-11-12 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_meta_ind'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meta_ind',
            new_name='Meta_vend',
        ),
    ]
