# Generated by Django 4.1.3 on 2022-11-13 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_meta_ind_meta_vend'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meta_vend',
            new_name='Metas',
        ),
        migrations.AddField(
            model_name='vendedor',
            name='metas',
            field=models.ManyToManyField(to='core.metas'),
        ),
    ]
